### PR TITLE
Update logontracer.py

### PR DESCRIPTION
**Pull request by falsneg**
replaced repetitive strptime conversions with convert_logtime and added a workaround to remove trailing timezone (with re.sub)

### CODE REVIEW

**Comment by shu-tom** [comment]
Is this re.sub a bug fix?

**Comment by falsneg** [comment]
Yeah I've had a log with a trailing timezone that required stripping

**Comment by shu-tom** [comment]
Could you show me an event log sample?

**Comment by falsneg** [comment]
I'm sorry, I cannot share the log in question as it belongs to a customer.

**Comment by shu-tom** [comment]
We will consider how to fix it after checking the log of this issue.

**Pull request closed without merging**
